CREATE DATABASE JeuPoint;

CREATE TABLE GameEventType
(
    GameEventTypeID SERIAL PRIMARY KEY,
    GameEventName VARCHAR(30) NOT NULL UNIQUE,
    Description VARCHAR(50),
    CreatedDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
 
CREATE TABLE Player
(
    PlayerID SERIAL PRIMARY KEY,
    PlayerName VARCHAR(100) NOT NULL,
    RegistrationDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
 
CREATE TABLE Game
(
    GameID SERIAL PRIMARY KEY,
    GameName VARCHAR(200) NOT NULL,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Notes VARCHAR(100)
);
 
CREATE TABLE GameEvent
(
    GameEventsID SERIAL PRIMARY KEY,
    GameID INTEGER NOT NULL,
    PlayerID INTEGER NOT NULL,
    GameEventTypeID INTEGER NOT NULL,
    PositionA POINT,
    PositionB POINT,
    AddedDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (GameID) REFERENCES Game(GameID),
    FOREIGN KEY (PlayerID) REFERENCES Player(PlayerID),
    FOREIGN KEY (GameEventTypeID) REFERENCES GameEventType(GameEventTypeID)
);

CREATE TABLE GameDetail(
    GameDetailsID SERIAL PRIMARY KEY,
    GameID INTEGER NOT NULL,
    PlayerID INTEGER NOT NULL
);

CREATE TABLE GameConfig
(
    GameConfigID SERIAL PRIMARY KEY,
    GameID INTEGER NOT NULL UNIQUE,
    BoardDimensionM INTEGER NOT NULL DEFAULT 9,
    TimePerPoint INTEGER NOT NULL DEFAULT 30,
    TimePerTurn INTEGER NOT NULL DEFAULT 60,
    CreatedDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (GameID) REFERENCES Game(GameID) ON DELETE CASCADE
);

 